feat: add docstring to get_pollution_history function
UBC-MDS/rpollution pull request #2
Opened 2022-01-20 05:35 UTC by mel-liow

2022-01-21 08:12 UTC, danfke requested changes
I'm writing the docstring for my function using the workflow in https://r-pkgs.org/whole-game.html#write-the-first-function. Using this workflow will automatically update other files and also creates a file for each function because of this each function should get its own file

2022-01-21 08:12 UTC, danfke commented on src/rpollution.R
> +#' @param lat Latitude coordinate for a given location as a float
Should be float or integer

2022-01-22 03:52 UTC, christopheralex requested changes
I think there has to be changes in the man file for the docstring as well . So as dan said , would be better if you follow the IAT2 guide.

2022-01-22 16:49 UTC, danfke approved these changes
Looks good thanks Mel!

2022-01-22 16:55 UTC, christopheralex approved these changes

2022-01-22 16:55 UTC, merged